before_test:
  - cinst Cygwin
test_script:
  - tests\tests.bat
  - bash ./tests/tests.sh
before_build:
  - cinst PyWin32
build_script:
  - cd python & build.bat & cd ..
platform:
  - x86
  - x64
before_deploy:
  - cinst 7zip.commandline
deploy_script:
  - bash release.sh
