platform:
  - x86
  - x64

before_build:
  - cinst PyWin32
build_script:
  - cd python & build.bat & cd ..

before_test:
  - cinst Cygwin
test_script:
  - cd tests & bash tests.sh ../../python/dist/gulp.exe
  - cd tests & bash tests.sh "bash ../../bash/gulp"

before_deploy:
  - cinst 7zip.commandline
deploy_script:
  - bash release.sh
