platform:
  - x86
  - x64

before_build:
  - cinst PyWin32
build_script:
  - cd python & build.bat & cd ..

before_test:
#  - cinst Cygwin
test_script:
  - cd tests & python tests.py ../../python/dist/gulp.exe
#  - cd tests & python tests.py "bash ../bash/gulp" & cd ..

before_deploy:
  - cinst 7zip.commandline
deploy_script:
  - bash release.sh
