environment:
  GITHUB_TOKEN:
    secure: cyhon2hMYiAUayELrLwKZsZ9YPLrjbmOvDOOxCuSoY9uJgJ75Pwb21gG4cDi76wH

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

platform:
  - x86

before_build:
  - cinst PyWin32 -force
build_script:
  - cd python & build.bat & cd ..

before_test:
  - cinst Cygwin
test_script:
  - cd tests & bash tests.sh ../../python/dist/gulp.exe & bash tests.sh "bash ../../bash/gulp" & cd ..

before_deploy:
  - cinst 7zip.commandline
deploy_script:
  - bash release.sh
