environment:
  GITHUB_TOKEN:
    secure: z9QncIJ4J0g1hQcwi364NWZXDyyVz3Q6gNVkra9pq5y+UuyWSJ0Pm6/Rf/cpvMDz

platform:
  - x86

before_build:
  - cinst PyWin32 -force
build_script:
  - cd python & build.bat & cd ..

before_test:
  - cinst Cygwin
test_script:
  - cd tests & bash tests.sh ../../python/dist/gulp.exe & bash tests.sh "bash ../../bash/gulp" & cd ..

before_deploy:
  - cinst 7zip.commandline
deploy_script:
  - bash release.sh
